// [REQ-CONFIG_DRIVEN_UI] [IMPL-CONFIG_LOADER] [IMPL-YAML_CONFIG]
// Unit tests for the configuration loader module. Validates YAML parsing,
// defaults merging, deep merge behavior, theme CSS generation, class
// overrides, and caching.

import { describe, it, expect, beforeEach } from "vitest";
import {
  getSiteConfig,
  getThemeConfig,
  getJobsConfig,
  generateThemeCss,
  getOverride,
  getJobsOverride,
  getStatusBadgeClass,
  _resetConfigCache,
  _deepMerge,
  _DEFAULT_SITE_CONFIG,
  _DEFAULT_THEME_CONFIG,
} from "./config";
import type { ClassOverrides, ThemeConfig } from "./config.types";

// Reset cache before each test to ensure isolation
beforeEach(() => {
  _resetConfigCache();
});

// ---------------------------------------------------------------------------
// Config loading and defaults
// ---------------------------------------------------------------------------

describe("getSiteConfig [REQ-CONFIG_DRIVEN_UI] [IMPL-CONFIG_LOADER]", () => {
  it("returns a complete SiteConfig object", () => {
    const config = getSiteConfig();
    expect(config).toBeDefined();
    expect(config.metadata).toBeDefined();
    expect(config.locale).toBeDefined();
    expect(config.branding).toBeDefined();
    expect(config.content).toBeDefined();
    expect(config.navigation).toBeDefined();
  });

  it("loads metadata from config [IMPL-YAML_CONFIG]", () => {
    const config = getSiteConfig();
    expect(config.metadata.title).toBe("Create Next App");
    expect(config.metadata.description).toBe("Generated by create next app");
  });

  it("loads locale from config [IMPL-YAML_CONFIG]", () => {
    const config = getSiteConfig();
    expect(config.locale).toBe("en");
  });

  it("loads branding from config [IMPL-YAML_CONFIG]", () => {
    const config = getSiteConfig();
    expect(config.branding.logo.src).toBe("/next.svg");
    expect(config.branding.logo.alt).toBe("Next.js logo");
    expect(config.branding.logo.width).toBe(100);
    expect(config.branding.logo.height).toBe(20);
  });

  it("loads content from config [IMPL-YAML_CONFIG]", () => {
    const config = getSiteConfig();
    expect(config.content.heading).toContain("get started");
    expect(config.content.description).toContain("{templates}");
  });

  it("loads navigation from config [IMPL-YAML_CONFIG]", () => {
    const config = getSiteConfig();
    expect(config.navigation.inlineLinks.templates).toBeDefined();
    expect(config.navigation.inlineLinks.learning).toBeDefined();
    expect(config.navigation.buttons.length).toBeGreaterThan(0);
    expect(config.navigation.security.target).toBe("_blank");
    expect(config.navigation.security.rel).toBe("noopener noreferrer");
  });

  it("caches the result on subsequent calls [IMPL-CONFIG_LOADER]", () => {
    const config1 = getSiteConfig();
    const config2 = getSiteConfig();
    // Same reference due to caching
    expect(config1).toBe(config2);
  });

  it("returns fresh config after cache reset [IMPL-CONFIG_LOADER]", () => {
    const config1 = getSiteConfig();
    _resetConfigCache();
    const config2 = getSiteConfig();
    // Different references after reset
    expect(config1).not.toBe(config2);
    // But same values
    expect(config1).toEqual(config2);
  });
});

describe("getThemeConfig [REQ-CONFIG_DRIVEN_UI] [IMPL-CONFIG_LOADER]", () => {
  it("returns a complete ThemeConfig object", () => {
    const config = getThemeConfig();
    expect(config).toBeDefined();
    expect(config.colors).toBeDefined();
    expect(config.fonts).toBeDefined();
    expect(config.spacing).toBeDefined();
    expect(config.sizing).toBeDefined();
    expect(config.overrides).toBeDefined();
  });

  it("loads light mode colors [IMPL-YAML_CONFIG]", () => {
    const config = getThemeConfig();
    expect(config.colors.light.background).toBe("#ffffff");
    expect(config.colors.light.foreground).toBe("#171717");
  });

  it("loads dark mode colors [IMPL-YAML_CONFIG]", () => {
    const config = getThemeConfig();
    expect(config.colors.dark.background).toBe("#0a0a0a");
    expect(config.colors.dark.foreground).toBe("#ededed");
  });

  it("loads font configuration [IMPL-YAML_CONFIG]", () => {
    const config = getThemeConfig();
    expect(config.fonts.sans.variable).toBe("--font-geist-sans");
    expect(config.fonts.sans.fallback).toBe("Arial, Helvetica, sans-serif");
    expect(config.fonts.mono.variable).toBe("--font-geist-mono");
  });

  it("loads spacing configuration [IMPL-YAML_CONFIG]", () => {
    const config = getThemeConfig();
    expect(config.spacing.page.paddingY).toBe("32");
    expect(config.spacing.page.paddingX).toBe("16");
    expect(config.spacing.contentGap).toBe("6");
    expect(config.spacing.buttonGap).toBe("4");
  });

  it("loads sizing configuration [IMPL-YAML_CONFIG]", () => {
    const config = getThemeConfig();
    expect(config.sizing.maxContentWidth).toBe("3xl");
    expect(config.sizing.buttonHeight).toBe("12");
    expect(config.sizing.buttonDesktopWidth).toBe("158px");
  });

  it("caches the result on subsequent calls [IMPL-CONFIG_LOADER]", () => {
    const config1 = getThemeConfig();
    const config2 = getThemeConfig();
    expect(config1).toBe(config2);
  });
});

// ---------------------------------------------------------------------------
// Deep merge utility
// ---------------------------------------------------------------------------

describe("deepMerge [IMPL-CONFIG_LOADER]", () => {
  it("returns target when source is empty", () => {
    const target = { a: 1, b: "hello" };
    const result = _deepMerge(target, {});
    expect(result).toEqual(target);
  });

  it("overwrites primitive values from source", () => {
    const target = { a: 1, b: "hello" };
    const result = _deepMerge(target, { a: 2 });
    expect(result).toEqual({ a: 2, b: "hello" });
  });

  it("deep merges nested objects", () => {
    const target = { nested: { x: 1, y: 2 } };
    const result = _deepMerge(target, { nested: { x: 10 } });
    expect(result).toEqual({ nested: { x: 10, y: 2 } });
  });

  it("replaces arrays entirely (not concatenating)", () => {
    const target = { items: [1, 2, 3] };
    const result = _deepMerge(target, { items: [4, 5] });
    expect(result).toEqual({ items: [4, 5] });
  });

  it("does not mutate target or source", () => {
    const target = { a: 1, nested: { x: 1 } };
    const source = { a: 2, nested: { y: 2 } };
    const targetCopy = JSON.parse(JSON.stringify(target));
    const sourceCopy = JSON.parse(JSON.stringify(source));
    _deepMerge(target, source);
    expect(target).toEqual(targetCopy);
    expect(source).toEqual(sourceCopy);
  });

  it("handles deeply nested structures", () => {
    const target = { a: { b: { c: { d: 1 } } } };
    const result = _deepMerge(target, { a: { b: { c: { d: 99 } } } });
    expect(result).toEqual({ a: { b: { c: { d: 99 } } } });
  });

  it("adds new keys from source", () => {
    const target = { a: 1 };
    const result = _deepMerge(target, { b: 2 });
    expect(result).toEqual({ a: 1, b: 2 });
  });

  it("skips undefined values in source", () => {
    const target = { a: 1 };
    const result = _deepMerge(target, { a: undefined });
    expect(result).toEqual({ a: 1 });
  });
});

// ---------------------------------------------------------------------------
// generateThemeCss
// ---------------------------------------------------------------------------

describe("generateThemeCss [REQ-CONFIG_DRIVEN_UI] [IMPL-THEME_INJECTION]", () => {
  it("generates valid CSS with light and dark mode variables", () => {
    const theme = getThemeConfig();
    const css = generateThemeCss(theme);

    // Contains :root for light mode
    expect(css).toContain(":root");
    expect(css).toContain("--background: #ffffff");
    expect(css).toContain("--foreground: #171717");

    // Contains dark mode media query
    expect(css).toContain("prefers-color-scheme: dark");
    expect(css).toContain("--background: #0a0a0a");
    expect(css).toContain("--foreground: #ededed");
  });

  it("includes custom color variables when present", () => {
    const theme: ThemeConfig = {
      ..._DEFAULT_THEME_CONFIG,
      colors: {
        light: { background: "#fff", foreground: "#000", accent: "#ff0000" },
        dark: { background: "#111", foreground: "#eee", accent: "#00ff00" },
      },
    };
    const css = generateThemeCss(theme);

    expect(css).toContain("--accent: #ff0000");
    expect(css).toContain("--accent: #00ff00");
  });
});

// ---------------------------------------------------------------------------
// getOverride
// ---------------------------------------------------------------------------

describe("getOverride [REQ-CONFIG_DRIVEN_UI] [IMPL-CLASS_OVERRIDES]", () => {
  it("returns empty string for undefined override key", () => {
    const overrides: ClassOverrides = {};
    expect(getOverride(overrides, "main")).toBe("");
  });

  it("returns empty string for blank override value", () => {
    const overrides: ClassOverrides = { main: "  " };
    expect(getOverride(overrides, "main")).toBe("");
  });

  it("returns trimmed override value when present", () => {
    const overrides: ClassOverrides = { main: " bg-red-500 " };
    expect(getOverride(overrides, "main")).toBe("bg-red-500");
  });

  it("returns correct value for each override key", () => {
    const overrides: ClassOverrides = {
      outerContainer: "custom-outer",
      main: "custom-main",
      heading: "custom-heading",
      paragraph: "custom-paragraph",
      contentSection: "custom-content",
      buttonGroup: "custom-buttons",
      primaryButton: "custom-primary",
      secondaryButton: "custom-secondary",
      inlineLink: "custom-link",
    };

    expect(getOverride(overrides, "outerContainer")).toBe("custom-outer");
    expect(getOverride(overrides, "main")).toBe("custom-main");
    expect(getOverride(overrides, "heading")).toBe("custom-heading");
    expect(getOverride(overrides, "paragraph")).toBe("custom-paragraph");
    expect(getOverride(overrides, "contentSection")).toBe("custom-content");
    expect(getOverride(overrides, "buttonGroup")).toBe("custom-buttons");
    expect(getOverride(overrides, "primaryButton")).toBe("custom-primary");
    expect(getOverride(overrides, "secondaryButton")).toBe("custom-secondary");
    expect(getOverride(overrides, "inlineLink")).toBe("custom-link");
  });
});

// ---------------------------------------------------------------------------
// Default configs structure
// ---------------------------------------------------------------------------

describe("Default configs [IMPL-YAML_CONFIG]", () => {
  it("DEFAULT_SITE_CONFIG has all required fields", () => {
    expect(_DEFAULT_SITE_CONFIG.metadata.title).toBeTruthy();
    expect(_DEFAULT_SITE_CONFIG.metadata.description).toBeTruthy();
    expect(_DEFAULT_SITE_CONFIG.locale).toBeTruthy();
    expect(_DEFAULT_SITE_CONFIG.branding.logo.src).toBeTruthy();
    expect(_DEFAULT_SITE_CONFIG.content.heading).toBeTruthy();
    expect(_DEFAULT_SITE_CONFIG.content.description).toBeTruthy();
    expect(Object.keys(_DEFAULT_SITE_CONFIG.navigation.inlineLinks).length).toBeGreaterThan(0);
    expect(_DEFAULT_SITE_CONFIG.navigation.buttons.length).toBeGreaterThan(0);
  });

  it("DEFAULT_THEME_CONFIG has all required fields", () => {
    expect(_DEFAULT_THEME_CONFIG.colors.light.background).toBeTruthy();
    expect(_DEFAULT_THEME_CONFIG.colors.dark.background).toBeTruthy();
    expect(_DEFAULT_THEME_CONFIG.fonts.sans.variable).toBeTruthy();
    expect(_DEFAULT_THEME_CONFIG.fonts.mono.variable).toBeTruthy();
    expect(_DEFAULT_THEME_CONFIG.spacing.page.paddingY).toBeTruthy();
    expect(_DEFAULT_THEME_CONFIG.sizing.maxContentWidth).toBeTruthy();
  });
});

// ---------------------------------------------------------------------------
// getJobsConfig [REQ-CONFIG_DRIVEN_APPEARANCE] [IMPL-CONFIG_DRIVEN_APPEARANCE]
// ---------------------------------------------------------------------------

describe("getJobsConfig [REQ-CONFIG_DRIVEN_APPEARANCE] [IMPL-CONFIG_LOADER]", () => {
  it("returns a complete JobsConfig object", () => {
    const config = getJobsConfig();
    expect(config).toBeDefined();
    expect(config.app).toBeDefined();
    expect(config.fields).toBeDefined();
    expect(config.table).toBeDefined();
    expect(config.copy).toBeDefined();
  });

  it("loads app title and description", () => {
    const config = getJobsConfig();
    expect(config.app.title).toBe("Job Search Tracker");
    expect(config.app.description).toContain("Track");
  });

  it("loads fields with applicationStatus options", () => {
    const config = getJobsConfig();
    const statusField = config.fields.find((f) => f.name === "applicationStatus");
    expect(statusField).toBeDefined();
    expect(statusField?.options?.length).toBeGreaterThan(0);
    expect(statusField?.options?.some((o) => o.value === "applied")).toBe(true);
  });

  it("loads copy strings for jobs UI", () => {
    const config = getJobsConfig();
    expect(config.copy?.listTitle).toBeTruthy();
    expect(config.copy?.addNewButton).toBeTruthy();
    expect(config.copy?.emptyTitle).toBeTruthy();
    expect(config.copy?.editLink).toBeTruthy();
  });

  it("caches the result on subsequent calls", () => {
    const config1 = getJobsConfig();
    const config2 = getJobsConfig();
    expect(config1).toBe(config2);
  });

  it("returns fresh config after cache reset", () => {
    const config1 = getJobsConfig();
    _resetConfigCache();
    const config2 = getJobsConfig();
    expect(config1).not.toBe(config2);
    expect(config1.app.title).toBe(config2.app.title);
  });
});

describe("getJobsOverride [REQ-CONFIG_DRIVEN_APPEARANCE]", () => {
  it("returns empty string for undefined overrides", () => {
    expect(getJobsOverride(undefined, "pageContainer")).toBe("");
  });

  it("returns empty string for missing key", () => {
    expect(getJobsOverride({}, "primaryButton")).toBe("");
  });

  it("returns trimmed override value when present", () => {
    expect(getJobsOverride({ card: " shadow-lg " }, "card")).toBe("shadow-lg");
  });
});

describe("getStatusBadgeClass [REQ-CONFIG_DRIVEN_APPEARANCE]", () => {
  it("returns class for known status from theme", () => {
    const theme = getThemeConfig();
    expect(getStatusBadgeClass(theme, "applied")).toContain("blue");
    expect(getStatusBadgeClass(theme, "rejected")).toContain("red");
  });

  it("returns default when status not in config", () => {
    const theme = getThemeConfig();
    const cls = getStatusBadgeClass(theme, "unknown");
    expect(cls).toBeTruthy();
    expect(typeof cls).toBe("string");
  });
});
