// [IMPL-CONFIG_LOADER] [ARCH-CONFIG_DRIVEN_UI] [REQ-CONFIG_DRIVEN_UI]
// Configuration loader module. Reads YAML files from config/ directory,
// validates against TypeScript types, merges with defaults, and exports
// typed configuration objects. Server-only – uses fs.readFileSync with
// module-level caching so files are read once per server start / HMR cycle.

import fs from "fs";
import path from "path";
import yaml from "js-yaml";
import type {
  SiteConfig,
  ThemeConfig,
  ClassOverrides,
  JobsConfig,
  JobsThemeOverrides,
} from "./config.types";

// ---------------------------------------------------------------------------
// Default configurations – used as fallback when YAML values are missing
// ---------------------------------------------------------------------------

// [IMPL-YAML_CONFIG] [REQ-CONFIG_DRIVEN_UI]
// Default site config mirrors the original hard-coded values from page.tsx / layout.tsx
const DEFAULT_SITE_CONFIG: SiteConfig = {
  metadata: {
    title: "Create Next App",
    description: "Generated by create next app",
  },
  locale: "en",
  branding: {
    logo: {
      src: "/next.svg",
      alt: "Next.js logo",
      width: 100,
      height: 20,
      darkInvert: true,
    },
  },
  content: {
    heading: "To get started, edit the page.tsx file.",
    description:
      "Looking for a starting point or more instructions? Head over to {templates} or the {learning} center.",
  },
  navigation: {
    inlineLinks: {
      templates: {
        label: "Templates",
        href: "https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app",
      },
      learning: {
        label: "Learning",
        href: "https://nextjs.org/learn?utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app",
      },
    },
    buttons: [
      {
        label: "Deploy Now",
        href: "https://vercel.com/new?utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app",
        variant: "primary",
        icon: {
          src: "/vercel.svg",
          alt: "Vercel logomark",
          width: 16,
          height: 16,
          darkInvert: true,
        },
      },
      {
        label: "Documentation",
        href: "https://nextjs.org/docs?utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app",
        variant: "secondary",
      },
    ],
    security: {
      target: "_blank",
      rel: "noopener noreferrer",
    },
  },
};

// [IMPL-YAML_CONFIG] [REQ-CONFIG_DRIVEN_UI]
// Default theme config mirrors the original hard-coded values from globals.css / page.tsx
const DEFAULT_THEME_CONFIG: ThemeConfig = {
  colors: {
    light: {
      background: "#ffffff",
      foreground: "#171717",
    },
    dark: {
      background: "#0a0a0a",
      foreground: "#ededed",
    },
  },
  fonts: {
    sans: {
      variable: "--font-geist-sans",
      fallback: "Arial, Helvetica, sans-serif",
    },
    mono: {
      variable: "--font-geist-mono",
      fallback: "monospace",
    },
  },
  spacing: {
    page: {
      paddingY: "32",
      paddingX: "16",
    },
    contentGap: "6",
    buttonGap: "4",
  },
  sizing: {
    maxContentWidth: "3xl",
    buttonHeight: "12",
    buttonDesktopWidth: "158px",
  },
  overrides: {},
  jobs: {
    overrides: {},
    statusBadges: {
      applied: "bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200",
      rejected: "bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200",
      interested: "bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200",
      to_apply: "bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200",
      none: "bg-gray-100 text-gray-800 dark:bg-gray-800 dark:text-gray-200",
    },
  },
};

// [IMPL-CONFIG_DRIVEN_APPEARANCE] [ARCH-CONFIG_DRIVEN_APPEARANCE] [REQ-CONFIG_DRIVEN_APPEARANCE]
// Default jobs config – used when config/jobs.yaml is missing or partial.
const DEFAULT_JOBS_CONFIG: JobsConfig = {
  app: {
    title: "Job Search Tracker",
    description: "Track open positions and applications",
  },
  fields: [
    { name: "title", label: "Position Title", type: "text", required: true, showInTable: true },
    { name: "postingDate", label: "Posting Date", type: "date", showInTable: true },
    { name: "urls", label: "URLs", type: "url-list", showInTable: false },
    { name: "description", label: "Description", type: "textarea", showInTable: false },
    {
      name: "applicationStatus",
      label: "Application Status",
      type: "select",
      showInTable: true,
      options: [
        { value: "none", label: "None" },
        { value: "interested", label: "Interested" },
        { value: "to_apply", label: "To Apply" },
        { value: "applied", label: "Applied" },
        { value: "rejected", label: "Rejected" },
      ],
    },
    { name: "statusDate", label: "Status Date", type: "date", showInTable: true },
    { name: "notes", label: "Notes", type: "textarea", showInTable: false },
  ],
  table: { defaultSort: "postingDate", defaultSortDirection: "desc" },
  copy: {
    listTitle: "Job Search Tracker",
    listSubtitle: "Track your job applications and positions",
    addNewButton: "Add New Position",
    emptyTitle: "No positions found.",
    emptyLink: "Create your first position",
    editLink: "Edit",
    editPageTitle: "Edit Position",
    backToList: "Back to List",
    backToCalendar: "Return to Calendar",
    deleteButton: "Delete Position",
    deleteConfirm: "Are you sure you want to delete this position?",
    newPageTitle: "Add New Position",
    newPageSubtitle: "Enter details about a new job position",
    positionDetails: "Position Details",
    applications: "Applications",
    addApplication: "Add Application",
    editApplication: "Edit Application",
    saveButton: "Save",
    updateButton: "Update",
    addButton: "Add",
    cancel: "Cancel",
    remove: "Remove",
    addUrl: "+ Add URL",
    createPosition: "Create Position",
    updatePosition: "Update Position",
    saving: "Saving...",
    // [REQ-JOB_TRACKER_CALENDAR] Calendar view copy defaults
    calendarTitle: "Calendar View",
    calendarSubtitle: "Positions and applications by date",
    calendarPrev: "Previous",
    calendarNext: "Next",
    calendarToday: "Today",
    calendarNoItems: "No items for this day",
    calendarPositionLabel: "Position",
    calendarApplicationLabel: "Application",
    calendarDetailClose: "Close",
    calendarBackToList: "Back to List",
    calendarDayNames: "Sun,Mon,Tue,Wed,Thu,Fri,Sat",
    calendarViewButton: "Calendar View",
  },
};

// ---------------------------------------------------------------------------
// Deep merge utility
// ---------------------------------------------------------------------------

/**
 * Deep-merges source into target. Arrays are replaced, not concatenated.
 * Returns a new object without mutating either input.
 */
// [IMPL-CONFIG_LOADER] Helper for merging partial user config with defaults
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function deepMerge<T>(target: T, source: Record<string, any>): T {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const result = { ...target } as Record<string, any>;
  for (const key of Object.keys(source)) {
    const sourceVal = source[key];
    const targetVal = result[key];
    if (
      sourceVal !== null &&
      sourceVal !== undefined &&
      typeof sourceVal === "object" &&
      !Array.isArray(sourceVal) &&
      targetVal !== null &&
      targetVal !== undefined &&
      typeof targetVal === "object" &&
      !Array.isArray(targetVal)
    ) {
      result[key] = deepMerge(targetVal, sourceVal);
    } else if (sourceVal !== undefined) {
      result[key] = sourceVal;
    }
  }
  return result as T;
}

// ---------------------------------------------------------------------------
// YAML file reader
// ---------------------------------------------------------------------------

/**
 * Reads and parses a YAML file. Returns an empty object if the file
 * does not exist (so the defaults are used in full).
 */
// [IMPL-CONFIG_LOADER] File reader with graceful fallback
function readYamlFile(filePath: string): Record<string, unknown> {
  try {
    const absolutePath = path.resolve(process.cwd(), filePath);
    const raw = fs.readFileSync(absolutePath, "utf-8");
    const parsed = yaml.load(raw);
    if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
      return parsed as Record<string, unknown>;
    }
    return {};
  } catch {
    // DEBUG: Config file not found or unreadable – using defaults
    return {};
  }
}

// ---------------------------------------------------------------------------
// Module-level cache
// ---------------------------------------------------------------------------

let _siteConfig: SiteConfig | null = null;
let _themeConfig: ThemeConfig | null = null;
let _jobsConfig: JobsConfig | null = null;

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Returns the resolved site configuration (config/site.yaml merged with defaults).
 * Result is cached at module level for the lifetime of the server process.
 *
 * [IMPL-CONFIG_LOADER] [ARCH-CONFIG_DRIVEN_UI] [REQ-CONFIG_DRIVEN_UI]
 */
export function getSiteConfig(): SiteConfig {
  if (_siteConfig) return _siteConfig;
  const userConfig = readYamlFile("config/site.yaml");
  const merged = deepMerge(DEFAULT_SITE_CONFIG, userConfig);
  _siteConfig = merged;
  return merged;
}

/**
 * Returns the resolved theme configuration (config/theme.yaml merged with defaults).
 * Result is cached at module level for the lifetime of the server process.
 *
 * [IMPL-CONFIG_LOADER] [ARCH-CONFIG_DRIVEN_UI] [REQ-CONFIG_DRIVEN_UI]
 */
export function getThemeConfig(): ThemeConfig {
  if (_themeConfig) return _themeConfig;
  const userConfig = readYamlFile("config/theme.yaml");
  const merged = deepMerge(DEFAULT_THEME_CONFIG, userConfig);
  _themeConfig = merged;
  return merged;
}

/**
 * Generates a CSS string that sets custom properties for light and dark modes
 * from the theme configuration. Intended to be injected via a <style> tag in
 * the root layout.
 *
 * [IMPL-THEME_INJECTION] [ARCH-THEME_INJECTION] [REQ-CONFIG_DRIVEN_UI]
 */
export function generateThemeCss(theme: ThemeConfig): string {
  const lightVars = Object.entries(theme.colors.light)
    .map(([key, value]) => `    --${key}: ${value};`)
    .join("\n");

  const darkVars = Object.entries(theme.colors.dark)
    .map(([key, value]) => `    --${key}: ${value};`)
    .join("\n");

  return `:root {\n${lightVars}\n  }\n  @media (prefers-color-scheme: dark) {\n    :root {\n${darkVars}\n    }\n  }`;
}

/**
 * Returns the resolved jobs configuration (config/jobs.yaml merged with defaults).
 * Result is cached at module level for the lifetime of the server process.
 *
 * [IMPL-CONFIG_DRIVEN_APPEARANCE] [ARCH-CONFIG_DRIVEN_APPEARANCE] [REQ-CONFIG_DRIVEN_APPEARANCE]
 */
export function getJobsConfig(): JobsConfig {
  if (_jobsConfig) return _jobsConfig;
  const userConfig = readYamlFile("config/jobs.yaml");
  const merged = deepMerge(DEFAULT_JOBS_CONFIG, userConfig);
  _jobsConfig = merged;
  return merged;
}

/**
 * Returns the resolved class string for a given override key, or empty string
 * if the override is not defined or blank.
 *
 * [IMPL-CLASS_OVERRIDES] [ARCH-CLASS_OVERRIDES] [REQ-CONFIG_DRIVEN_UI]
 */
export function getOverride(
  overrides: ClassOverrides,
  key: keyof ClassOverrides,
): string {
  return (overrides[key] ?? "").trim();
}

/**
 * Returns the class string for a jobs theme override key, or empty string if not set.
 * [IMPL-CONFIG_DRIVEN_APPEARANCE] [ARCH-CONFIG_DRIVEN_APPEARANCE] [REQ-CONFIG_DRIVEN_APPEARANCE]
 */
export function getJobsOverride(
  overrides: JobsThemeOverrides | undefined,
  key: keyof JobsThemeOverrides,
): string {
  return (overrides?.[key] ?? "").trim();
}

/**
 * Returns the status badge class for a status value from theme.jobs.statusBadges.
 * Falls back to statusBadgeDefault or a neutral default if not in config.
 * [IMPL-CONFIG_DRIVEN_APPEARANCE] [ARCH-CONFIG_DRIVEN_APPEARANCE] [REQ-CONFIG_DRIVEN_APPEARANCE]
 */
export function getStatusBadgeClass(
  theme: ThemeConfig,
  status: string,
): string {
  const badges = theme.jobs?.statusBadges;
  const overrides = theme.jobs?.overrides;
  const defaultClass =
    getJobsOverride(overrides, "statusBadgeDefault") ||
    "bg-gray-100 text-gray-800 dark:bg-gray-800 dark:text-gray-200";
  if (!badges) return defaultClass;
  return (badges[status] ?? badges["none"] ?? defaultClass).trim();
}

// ---------------------------------------------------------------------------
// Exports for testing – allow cache reset
// ---------------------------------------------------------------------------

/** @internal Reset cached configs – used only in tests */
export function _resetConfigCache(): void {
  _siteConfig = null;
  _themeConfig = null;
  _jobsConfig = null;
}

/** @internal Exposed for unit tests */
export { deepMerge as _deepMerge, readYamlFile as _readYamlFile };

/** @internal Default configs exposed for test assertions */
export {
  DEFAULT_SITE_CONFIG as _DEFAULT_SITE_CONFIG,
  DEFAULT_THEME_CONFIG as _DEFAULT_THEME_CONFIG,
  DEFAULT_JOBS_CONFIG as _DEFAULT_JOBS_CONFIG,
};
