// [IMPL-ROOT_LAYOUT] [ARCH-LAYOUT_PATTERN] [REQ-ROOT_LAYOUT]
// Root layout component that wraps all pages with consistent HTML structure,
// font configuration, and global styles. Uses Next.js App Router layout pattern.

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// [IMPL-FONT_LOADING] [ARCH-GOOGLE_FONTS] [REQ-FONT_SYSTEM]
// Load Geist Sans font with next/font optimization. Creates CSS variable
// for global font usage. Includes only Latin subset to minimize file size.
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// [IMPL-FONT_LOADING] [ARCH-GOOGLE_FONTS] [REQ-FONT_SYSTEM]
// Load Geist Mono font for code/monospace text. Creates CSS variable for
// flexible application throughout the codebase.
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// [IMPL-METADATA] [ARCH-NEXTJS_FRAMEWORK] [REQ-METADATA]
// Static metadata exported for SEO. Defines default page title and description
// that appear in browser tabs, bookmarks, and search engine results.
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// [IMPL-ROOT_LAYOUT] [ARCH-LAYOUT_PATTERN] [REQ-ROOT_LAYOUT]
// Root layout function that defines the HTML document structure. Renders once
// per application load and persists across page navigation. Server component
// by default (no client JavaScript unless "use client" is added).
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
